import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1e1e1e',
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#2c3e50',
  },
  container: {
    width: '90%',
    padding: 30,
    borderRadius: 15,
    backgroundColor: '#ecf0f1',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
  },
  textHeader: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#3498db',
    marginBottom: 30,
    textAlign: 'center',
  },
  textLabel: {
    fontSize: 20,
    color: '#2c3e50',
    marginBottom: 10,
  },
  textInput: {
    height: 60,
    borderColor: '#3498db',
    borderWidth: 2,
    borderRadius: 30,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    marginVertical: 10,
    fontSize: 18,
    color: '#2c3e50',
  },
  button: {
    height: 60,
    borderRadius: 30,
    backgroundColor: '#e74c3c',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  productItem: {
    padding: 20,
    borderBottomColor: '#dcdcdc',
    borderBottomWidth: 1,
    backgroundColor: '#34495e',
    borderRadius: 15,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  itemTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ecf0f1',
  },
  itemDetails: {
    fontSize: 20,
    color: '#bdc3c7',
  },
  itemBadge: {
    fontSize: 22,
    color: '#2ecc71',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  itemBadgeError: {
    color: '#e74c3c',
  },
  page: {
    flex: 1,
    backgroundColor: '#2c3e50',
    padding: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 15,
  },
  col: {
    flexGrow: 1,
    fontSize: 18,
    color: '#ecf0f1',
  },
  colAuto: {
    fontSize: 18,
    color: '#ecf0f1',
  },
  stockError: {
    color: '#e74c3c',
  },
  text: {
    fontSize: 18,
    color: '#ecf0f1',
  },
  header: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#3498db',
    marginBottom: 20,
    textAlign: 'center',
  },
});
